Include vector as it is used in this header file.
```
In file included from frameworks/base/libs/hwui/jni/fonts/Font.cpp:17:
In file included from frameworks/base/libs/hwui/jni/fonts/Font.h:19:
In file included from frameworks/minikin/include/minikin/FontVariation.h:22:
In file included from frameworks/minikin/include/minikin/SortedPackedVector.h:22:
frameworks/minikin/include/minikin/PackedVector.h:45:29: error: no template named 'vector' in namespace 'std'
   45 |     PackedVector(const std::vector<T>& src) : PackedVector() {
      |                        ~~~~~^
In file included from frameworks/base/libs/hwui/jni/fonts/Font.cpp:17:
In file included from frameworks/base/libs/hwui/jni/fonts/Font.h:19:
In file included from frameworks/minikin/include/minikin/FontVariation.h:22:
frameworks/minikin/include/minikin/SortedPackedVector.h:36:35: error: no template named 'vector' in namespace 'std'
   36 |     SortedPackedVector(const std::vector<T>& vec, bool sorted = false) : mPacked(vec) {
      |                              ~~~~~^
2 errors generated.
```

Flag: EXEMPT (bug 353528991)

Change-Id: I8f035c304b95e1e2164abdc9a1abdae95847cd11